[env:rpipico2-riscv]
board = rpipico2
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.mcu = rp2350-riscv
board_build.core = earlephilhower
build_flags =
	-DUSE_TINYUSB
	-DCFG_TUSB_RHPORT0_MODE


lib_deps =
  # RECOMMENDED
  # Accept new functionality in a backwards compatible manner and patches
  adafruit/Adafruit TinyUSB Library @ 3.4.5
  adafruit/Adafruit NeoPixel @ 1.13.0
  # adafruit/Adafruit SSD1306 @ 2.5.14   -- 已替换为本地 U8g2